export ROCM_PATH="$(rocm-sdk path --root)"
export ROCM_HOME="${ROCM_PATH}"
export HIP_PATH="${ROCM_PATH}"
export PYTORCH_ROCM_ARCH="gfx1201"
export VLLM_TARGET_DEVICE="rocm"
export CMAKE_GENERATOR="Ninja"
export CMAKE_PREFIX_PATH="$(rocm-sdk path --cmake):${CMAKE_PREFIX_PATH:-}"
export PATH="$(rocm-sdk path --bin):${PATH}"
export PYTHONPATH="${PIXI_PROJECT_ROOT}/vllm:${ROCM_PATH}/share/amd_smi${PYTHONPATH:+:${PYTHONPATH}}"
export LD_LIBRARY_PATH="${CONDA_PREFIX}/lib:${ROCM_PATH}/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
gcc_toolchain="${CONDA_PREFIX}/lib/gcc/x86_64-conda-linux-gnu/$(x86_64-conda-linux-gnu-c++ -dumpfullversion)"
gcc_cxx_include="${gcc_toolchain}/include/c++"
export CPLUS_INCLUDE_PATH="${gcc_cxx_include}:${gcc_cxx_include}/x86_64-conda-linux-gnu${CPLUS_INCLUDE_PATH:+:${CPLUS_INCLUDE_PATH}}"
export LIBRARY_PATH="${gcc_toolchain}${LIBRARY_PATH:+:${LIBRARY_PATH}}"
export LDFLAGS="${LDFLAGS:-} -Wl,--sysroot=${CONDA_BUILD_SYSROOT}"
# HIP's Clang must use the same C headers and linker sysroot as Conda GCC.
export HIPFLAGS="--sysroot=${CONDA_BUILD_SYSROOT} ${HIPFLAGS:-}"
